# Generated by Django 3.2.8 on 2021-10-28 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
